### ISSUE TITLE
Add documentation on Stores

### ISSUE THREAD

**Issue by connor11528** [trailsjs/doc#14]
I am working to get the mongoose trailpack setup and have an error about `Error: Migrate must be configured to either "create" or "drop"` where I believe I need to configure a Store. It would be nice to have so documentation pointing to a file path in the project where I must configure my Stores. Thank you!

**Comment by connor11528** [comment]
referencing issue [trailpack-mongoose#12](https://github.com/trailsjs/trailpack-mongoose/issues/12)

**Comment by disciple-dev** [comment]
For what it's worth, `none` is also an option.
