### ISSUE TITLE
Off line doc 

### ISSUE THREAD

**Issue by jaumard** [trailsjs/doc#3]
It would be nice to have the possibility to have off line documentation. I use Dash to sync all my documentations off line (https://kapeli.com/docsets) there a lot of doc like npm or express in it. Can be cool to have Trails also.

**Comment by maissani** [comment]
I agree with you Zeal, Dash and other offline Docs tools would be a nice feature.
I will work on it as soon as possible. 
I have to finish Alpha Doc first, and there is a lot of work, until i end it. 
Cordialy, 
Mehdi AISSANI

**Comment by disciple-dev** [comment]
+1 for Dash!
