### ISSUE TITLE
Chore v1.0 : Implement Concepts

### ISSUE THREAD

**Issue by maissani** [trailsjs/doc#5]
# Feature Concepts
## Who can contribute?

Any people can contribute on docs.
## What's needed

(This issue will be updated each time something is finish or created)
The following list describe what's our needs for the V1.0 of the docs:
- [ ] Configuration
- [ ] Controllers
- [ ] Footprints
- [ ] Internationalization
- [ ] Models
- [x] Policies ( Locked until get more info about koa https://github.com/trailsjs/trails-docs/pull/4) by @maissani
- [x] Routing ( currently in progress and discution at https://github.com/trailsjs/trails-docs/pull/7) by @maissani
- [ ] Services
- [ ] Sessions 
- [ ] Trailpacks
- [ ]  WebServers
## Eplainations:

One PR for each features because of unobstrusive contributing and fastest releasing docs.
Double check, you have to Assignee your PR to someone, docs has to be always double or sometimes triple check.
### The Currently in progress status

The developper is currently working on it, realeases has to pass the double verification to be merged.
### The Locked status

When docs are merged and wait for beeing reopened cause something could be missing.

**Comment by jaumard** [comment]
@trailsjs/maintainers feel free to pick one and help with this as you have the best vision of the framework :)

**Comment by konstantinzolotarev** [comment]
I see some problems with Models/ORM because there are several totally different ORM trailpacks that have different way of models description. And lot of other parts of trails has framework/library specific configs and features.
We might be need to create some basic description and list of available trailpacks with detailed docs per trailpack.

**Comment by jaumard** [comment]
@konstantinzolotarev I agree with you. Docs per trailpack need to be where ? In this repo or each trailpack should have his own `docs` folder ? 

Also for policies https://github.com/trailsjs/trails-docs/blob/master/concepts/policies/README.md we put Hapi and Express version, do you think it's correct (Controller will work like this too) or it will be better to put an Introduction and add only a link to the specific trailpacks instead ?

**Comment by konstantinzolotarev** [comment]
@jaumard I'd prefer each trailpack has it's own `docs` folder. We will be able to load in somewhere in docs website. And maintainers of trailpack will be able to write docs without need to change repo and search something.

**Comment by jaumard** [comment]
@konstantinzolotarev sounds good for me :) we will change this. 
Trailpack `docs` folder must have same file structure, something like 
- docs
  - concepts
    - policies
    - controllers
    - models
    - configuration
    - ....

**Comment by konstantinzolotarev** [comment]
@jaumard I think we need to create some sample for this.

**Comment by jaumard** [comment]
@konstantinzolotarev also maybe `generator-trailpack` can add a command to generate the folder structure of trailpack depends of they extends `trailpack` `trailpack-webserver` or `trailpack-datastore`

**Comment by konstantinzolotarev** [comment]
@jaumard sorry was without internet for several days.
I think it's good idea could you create issue there ? I'll do tomorrow

**Comment by jaumard** [comment]
@konstantinzolotarev no problem :) here it is https://github.com/trailsjs/generator-trailpack/issues/9

**Comment by maissani** [comment]
Hi @trailsjs/maintainers,

Now part of docs that belongs to be trailpack-specific belongs to be in respective trailpacks. 

As you can see in https://github.com/trailsjs/trailpack-express you can see that /docs/concepts/policies who contains policies docs for express, 
A small reference to this docs are done there : https://github.com/trailsjs/trails-docs/tree/master/concepts/policies
This aim the ability to auto-generate docs website from github docs as everybody nows there. 

Docs is realy helpfull for people that try do dive in trailsJS Framework and mandatory to get the best developper exprerience. 

That's why, i'm asking for help, and any kind of help, from validating docs to writing them. 

Best Regards, 
Mehdi AISSANI

**Comment by jaumard** [comment]
What is the purpose of Tags section ? https://github.com/trailsjs/trails-docs/tree/master/anatomy/trailsProject/api#tags don't know what to write there...

**Comment by scott-wyatt** [comment]
@maissani I will try and contribute to this.

**Comment by jaumard** [comment]
@maissani @scott-wyatt I working on the anatomy

**Comment by jaumard** [comment]
@maissani what is Dependency Injection for Trails ?
For me ORM and Models are duplicate part
Config and Environment are one part for me (or env sub part of config)
Modularity is part of Trailpacks, a full part looks to much ^^
