### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by wbprice** [trailsjs/doc#8]
I want to be able to publish these docs to NPM so I can build out the documentation section on trailsjs/trailsjs.io and have it mirror these docs.

**Comment by jaumard** [comment]
You can simply clone the repo and build the doc right ? Like smokesignals repo do with the tests. Because for now there only this repo but later all trailpacks will embed it's own documentation so deploy this doc on npm will not help for building the doc later. What do you think ?

**Comment by wbprice** [comment]
My goal is to have the docs section on `trailsjs.io` update itself automatically with the latest documentation from these (and other) markdown files whenever we redeploy the site.  If we at least add `package.json` to this repo, `trailsjs.io` can grab updates when we deploy.

**Comment by jaumard** [comment]
Hum I see, that's mean that this repo need to retrieve all markdown from trailpack and build file structure of the doc before publishing on npm. 
TravisCI is disabled on this repo. Only @tjwebb can configure it in order to publish the repo on npm.

**Comment by maissani** [comment]
:) I agree, my next update of docs will be soon.
 @jaumard can you check routing concept in my forked repo ?
