### ISSUE TITLE
Deployment section

### ISSUE THREAD

**Issue by jaumard** [trailsjs/doc#9]
Add a deployment section with : 
- General : 
  - Think about disabling trailpack-repl for security reason
  - Host must be set to your hostname (or 0.0.0.0) in config/web.js for Express
- on Heroku:
  - Trailpack-repl must be disabled in config/main.js or server will not start

**Comment by maissani** [comment]
# How to Deploy a TrailsJS App

Where this doc should be ?

General Heroku, behind and what about behind nginx proxy ?

**Comment by jaumard** [comment]
I think this is should be a full section. For now General and Heroku should be enough, because nginx proxy have nothing to do with Trails, it's just nginx configuration so maybe an example should be useful but if it's to put nginx conf in Trails docs...

**Comment by maissani** [comment]
I's open for contribution at #11 issue ( Updated issue to follow what's need to be done ).
